<?php
/**
 * @category    SwiftOtter
 * @author      Abdelrahman Emad <abdulrahman3mad@gmail.com
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var SwiftOtter\CustomerCollection\Model\CollectionItem $item
 */

/** @var SwiftOtter\CustomerCollection\ViewModel\Customer\CollectionList $viewModel */
$viewModel = $block->getData("view_model");
$items = $viewModel->getCollectionItems();
?>

<?php if(empty($items)): ?>
    <div class="message info empty">
        <span><?=$escaper->escapeHtml(__("You have no items in your collection"))?></span>
    </div>
<?php endif; ?>

<?php foreach($items as $item): ?>
    <div class="collection_item">
        <!-- Product Name -->
        <div>
            <span><?=$escaper->escapeHtml(__("Product name"))?></span>
            <a href="<?=$escaper->escapeHtmlAttr($item->getProduct()->getProductUrl())?>">
                <p class="collection_item_product_name"><?=$escaper->escapeHtml(__($item->getProduct()->getName()))?></p>
            </a>
        </div>

        <!-- Customer Comment -->
        <div>
            <span><?=$escaper->escapeHtml(__("Your comment"))?></span>
            <p class="collection_item_comment"><?=$escaper->escapeHtml(__($item->getComment()))?></p>
        </div>
    </div>
<?php endforeach; ?>
